### ISSUE TITLE
Visualise roads (with casualty data) in eatlas

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/saferactive#7] opened 2020-05-01 10:51 UTC

**Comment by mem48** [comment] 2020-05-01 14:43
@layik I've extracted data for london from www.cyipt.bike and output as a zipped geojson file [here](https://github.com/saferactive/cyipt) (see readme for details)

**Comment by layik** [comment] 2020-05-02 23:27
Thanks @mem48 will check it out and report back.

**Comment by layik** [comment] 2020-05-12 19:48
Hi @mem48 and team. So with newly added `gp_explore` function of `geoplumber` you too should be able to explore any `sf` object.

As for the data Malcolm generated over a week ago. It is over 300mb unzipped, so that is not what we can play with in one shot on a browser tab. I m not sure if I were to develop a node based "native" app whether we could still do that using JavaScript but JS keeps surprising me.

Right, so I wrote these lines to get 10k sample on the eatlas. It obviously can visualise it, though not many "settings" for lines so that needs to be done, not even colorscheme for example.

1. Do we want to serve the 300mb? If YES, then we need to generate tiles and view those tiles somewhere. Or we will have to slice according to some other geographic/screen limitation.
2. Will we have mix of lines and points or better, any idea of what kind of geometries we will be dealing with?

I think those two questions are enough for now.

```
l = "https://github.com/saferactive/cyipt/blob/master/london_cyipt.zip"
f = "~/Downloads/london_cyipit.zip"
d = "~/Desktop/data/cyipt"
dir.create(d)
download.file(l, destfile = f)
unzip(f, exdir = d)
list.files(d)
#> [1] "london_cyipt.geojson"
sf = sf::st_read(list.files(d, full.names = TRUE)[1])
length(sf)
#> [1] 27
nrow(sf)
#> [1] 444250
names(sf)
# [1] "osmid"              "name"
# [3] "ref"                "highway"
# [5] "junction"           "elevation"
# [7] "maxspeed"           "segregated"
# [9] "pctcensus"          "pctgov"
# [11] "pctgen"             "pctdutch"
# [13] "pctebike"           "pcttotal"
# [15] "ncollisionsSlight"  "ncollisionsSerious"
# [17] "ncollisionsFatal"   "bikeCasSlight"
# [19] "bikeCasSerious"     "bikeCasFatal"
# [21] "totalCasSlight"     "totalCasSerious"
# [23] "totalCasFatal"      "totalVeh"
# [25] "aadt"               "ncycles"
# [27] "geometry"
sf_10k = sf[sample(nrow(sf), 1e4),]
sf::st_write(file.path(d, "lc_10k.geojson"))

library(geoplumber)
# make sure you are in a gp project
gp_is_wd_geoplumber()
#> [1] TRUE
gp_explore(sf = sf_10k, browser = TRUE)
```

The image shows setting column to "name" and filtering by road speed "30". 
<img width="1538" alt="Screenshot 2020-05-12 at 20 39 07" src="https://user-images.githubusercontent.com/408568/81738451-a3f2f980-9491-11ea-8839-f1b5d7a95c39.png">

**Comment by mem48** [comment] 2020-05-12 20:57
Looks very exciting will give it a test tomorrow.  I assume we would also want to visualise point data. Perhaps just the things you have already developed would be enough to get started.

**Comment by Robinlovelace** [comment] 2020-05-13 11:40
Awesome work Layik.

**Comment by layik** [comment] 2020-05-13 23:29
Can do the whole thing of _actually_ just cannot transfer over network.

<img width="1673" alt="Screenshot 2020-05-14 at 00 29 05" src="https://user-images.githubusercontent.com/408568/81876176-f3145980-9579-11ea-9df3-36b5b86b1970.png">

**Comment by mem48** [comment] 2020-05-15 09:10
I don't see any way to serve 300MB without vector tiles or equivalent. Adopting early would future proof the prototype for national/ international rollout. 

Building tiles for just London should be quick, so I don't see a problem in slowing down rapid prototyping.

It also means we just need agreement on column names, then Layik can work on visualisation and UI unimpeded by the data analysis side.

**Comment by Robinlovelace** [comment] 2020-05-15 09:41
+1 to that @mem48 good thinking.

**Comment by Robinlovelace** [comment] 2020-05-15 09:43
Would you be able to fire off a script to build vector tiles for that test dataset? Or at least some starter code, happy to try building a vectortile dataset on my desktop.

**Comment by layik** [comment] 2020-05-15 11:26
Right, this should finish the blogpost @mem48 and @Robinlovelace. Also means a new step for the front-end but support is there from current libraries.

I will (not right now) get on with copying the tutorial code and do as much as possible in R.

**Comment by layik** [comment] 2020-05-15 11:27
support is there = Mapbox are the developers of [`tippecanoe`](https://github.com/mapbox/tippecanoe) etc.

**Comment by layik** [comment] 2020-05-15 11:38
ping https://github.com/ITSLeeds/VectorTiles

**Comment by Robinlovelace** [comment] 2020-05-15 12:03
Looking good. I don't have time to build vector tiles today but look forward to see a prototype of the roads served as vectortiles based on the approach outlined in that article, looking great.

**Comment by layik** [comment] 2020-05-15 12:23
<img width="1256" alt="Screenshot 2020-05-15 at 13 18 48" src="https://user-images.githubusercontent.com/408568/82049801-e6455200-96ae-11ea-8e14-7863845aac0b.png">

**Comment by layik** [comment] 2020-05-15 12:24
gzipped output is ~12mb! Distribute it on an iOS/Android app even!

**Comment by Robinlovelace** [comment] 2020-05-15 12:30
Mint!

**Comment by layik** [comment] 2020-07-21 20:02
Right, so as I am finally starting work on both SaferActive and our (SPENSER) scheduled for April work (COVID took over), I am now able to play with Mapbox Vector Tiles properly. Here are the large (300mb) data explored with ease in tiles, and data driven styling ([as they call it](https://docs.mapbox.com/mapbox-gl-js/example/data-driven-lines/)).

The all gray with thick lines shows line thickness represents number of slight injuries on each road to bikers. Spot the bridges?

<img width="1076" alt="Screenshot 2020-07-21 at 20 55 26" src="https://user-images.githubusercontent.com/408568/88100902-233d3180-cb95-11ea-81a4-f169c5140528.png">
<img width="1077" alt="Screenshot 2020-07-21 at 20 56 08" src="https://user-images.githubusercontent.com/408568/88100909-246e5e80-cb95-11ea-8eb6-6774a8115761.png">
<img width="1077" alt="Screenshot 2020-07-21 at 20 54 53" src="https://user-images.githubusercontent.com/408568/88100886-1d475080-cb95-11ea-9c1c-73fb1b75a1c0.png">


lighting things up in 2.5D?
<img width="1074" alt="Screenshot 2020-07-21 at 21 01 32" src="https://user-images.githubusercontent.com/408568/88101099-68616380-cb95-11ea-8b73-da8f83f30271.png">

Interaction and integrating it into eAtlas next.

**Comment by Robinlovelace** [comment] 2020-07-22 08:02
Looking good @layik ! Do you have Docker container or other way to give this a spin locally?

**Comment by layik** [comment] 2020-07-22 09:23
Hi @Robinlovelace. Yes we can juset sent a [commit](https://github.com/saferactive/saferactive-eatlas) except for autogenerating the tiles.

I am afraid you need to generate the tiles, I could change the Dockerfile to take care of that too, but that would be a full day's work which would be wasted as we _may_ not end-up using tiles and serving tiles.

To do that, inside `saferactive/saferactive-eatlas/public` you need to have a `london` tiles from the blogpost we wrote with @mem48 and then the Dockerfile should serve everything including the tiles.

To do that: 
1. grab the london casualty data/or any data in geojson
2. run the `tippecanoe -zg --output-to-directory=mytiles --drop-densest-as-needed --no-tile-compression msoa.geojson` command in the blogpost
3. make sure the tiles folder is called `tiles` if london data is used

That should get you this:
<img width="1023" alt="Screenshot 2020-07-22 at 10 14 02" src="https://user-images.githubusercontent.com/408568/88159534-54ede100-cc05-11ea-8a9d-db672f6563e6.png">

**Comment by mem48** [comment] 2020-07-22 10:19
Hi @layik you might have come across this already but I've been playing with the `tippecanoe` options. Some interesting ones to look at are:

`--coalesce-smallest-as-needed` for polygons merges rather than drops small polygons, so you don't have gaps in busy areas

`--simplification=10` you can adjust the amount of geometry simplification 

`--detect-shared-borders` for polygons: improved appearance of simplification


When viewing the LSOAs nationally the London area needs heavy simplification (notice the massive squares)

![image](https://user-images.githubusercontent.com/15819577/88164581-38a17280-cc0c-11ea-9943-fab003aca013.png)

So I'm thinking of using:

`--maximum-tile-bytes=1000K` increases the max tile size (default 500 KB) 

Of the 24,500 tiles needed old a few hundred hit the 500 KB limit, so adding a few extra MB of download should not be a big issue. Especially as it will be cached. 

Youg might not have the same problem with the larger MSOA but wanted to make a note in case it was useful.

Also `tippecanoe` works really well with Windows Subsystem for Linux. I know not directly relevant for you, but would be worth documenting in the blog post as it massively reduces the barrier for entry for Windows users.

**Comment by Robinlovelace** [comment] 2020-07-22 10:37
Could you write a bash script that does each of those stages for reproducibility? Looking really good.

**Comment by mem48** [comment] 2020-07-22 10:43
THis is my script for making vector tiles
```
cd /mnt/d/GitHub/creds2/CarbonCalculator/data
tippecanoe -zg --output-to-directory=mytiles2 --coalesce-smallest-as-needed --simplification=10 --detect-shared-borders LSOA_v1.geojson
```

**Comment by Robinlovelace** [comment] 2020-07-22 10:44
Nice and simple! And then you just need to upload the results to a suitable endpoint, e.g. GitHub pages, I imagine. Fantastic if so.

**Comment by mem48** [comment] 2020-07-22 10:46
I think for github pages you would have to disable gzip compression, as you can't modify the HTML headers, but any normal file server will do.

**Comment by Robinlovelace** [comment] 2020-07-22 10:49
Update, the above maps are serving data from here I think: https://github.com/saferactive/cyipt

We'll need to change that with updated data, do the variable names matter? And how easy is it to add summary graphics of the area currently in the map window (or selected by the user, that would be great if we could add a polygon tool as demonstrated here https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/ )?

We have a budget for a server so once we've got a reproducible Dockerfile or similar to test we can put this up :rocket:

**Comment by layik** [comment] 2020-07-22 11:00
Thanks Malcolm will definitely note these and we must get them into the blog post.

Robin, a couple of things:

- definitely reproducible, whether automated is something else
- do NOT worry about tile serving, the Dockerfile will serve it to the front end

So as soon as you have the tiles, which I hope with the `crashes_active_london.geojson` would lead to exactly the same "layers", I have referenced, then you will have the same image.

One more time, reproducible and automated are not the same. If we had a production server and we were 100% sure, then I am happy to change the Dockerfile to automate/make reproducible *everything*.

**Comment by Robinlovelace** [comment] 2020-07-22 11:03
Great, it terms of reproducibility is there a script in https://github.com/saferactive/saferactive-eatlas/ that serves the result? Looking at the README. Happy to give it a try to test reproducibility on a different computer.

**Comment by layik** [comment] 2020-07-22 11:05
Yes, both [Dockerfile](https://github.com/saferactive/saferactive-eatlas/blob/master/Dockerfile) and without Docker just using R, the [run.R](https://github.com/saferactive/saferactive-eatlas/blob/master/run.R) should work be 100% reproducible. If you use the `run.R` then as documented in README one needs to first build the front end using `gp_build` only once.

**Comment by Robinlovelace** [comment] 2020-07-22 11:07
Will give it a go and report back, starting with 

```
cd ~/saferactive/saferactive-eatlas
git pull
```

**Comment by Robinlovelace** [comment] 2020-07-22 11:08
Just running 

```
Rscript 'run.R'  
```

**Comment by Robinlovelace** [comment] 2020-07-22 11:09
Result:

```
[[1]]
[1] "plumber"   "stats"     "graphics"  "grDevices" "utils"     "datasets" 
[7] "methods"   "base"     

Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
Warning message:
In readLines(file) : incomplete final line found on 'R/plumber.R'
Starting server to listen on port 8000
```

**Comment by layik** [comment] 2020-07-22 11:09
Great, if it was never built, then must do `gp_build` before that. Updating README slightly to reflect that.

**Comment by Robinlovelace** [comment] 2020-07-22 11:10
So far so good. I see 

![image](https://user-images.githubusercontent.com/1825120/88169711-4fe45e00-cc14-11ea-9530-964f53c6b474.png)

**Comment by layik** [comment] 2020-07-22 11:10
:) nothing! tried the build step yet?

**Comment by Robinlovelace** [comment] 2020-07-22 11:11
Running 

```
Rscript -e 'geoplumber::gp_build()'
Running: npm run build

> eatlas@0.1.0 build /mnt/57982e2a-2874-4246-a6fe-115c199bc6bd/orgs/saferactive/saferactive-eatlas
> react-scripts build


```

**Comment by Robinlovelace** [comment] 2020-07-22 11:12
Taking its time on this step:

```
Creating an optimized production build...
```

**Comment by Robinlovelace** [comment] 2020-07-22 11:16
It still shows a blank screen after the following commands:

```zsh
Rscript -e 'geoplumber::gp_build()'
Rscript 'run.R'
```

This is what I have in the directory, do I need to create the `tiles` directory first?

```
ls   
build  casualties_active_london.Rds  Dockerfile  node_modules  package.json  package-lock.json  public  R  README.md  README.Rmd  run.R  saferactive-eatlas.Rproj  src
```

**Comment by Robinlovelace** [comment] 2020-07-22 11:17
Probably worth documenting in the README.

**Comment by Robinlovelace** [comment] 2020-07-22 11:20
Or is it the mapbox API key...

**Comment by Robinlovelace** [comment] 2020-07-22 11:20
> Or is it the mapbox API key...

That should just be for the proprietary basemaps.

**Comment by layik** [comment] 2020-07-22 11:25
Just bear with me please. It is the location of the tiles, editing above comment to reflect this. The tiles must be in the same location of the build which is `build` not `public`. Sending the minor changes in the repo and update above comment.

**Comment by layik** [comment] 2020-07-22 11:26
Could you please pull and just `gp_plumb` again, at leas you should see the data but no tiles.

**Comment by Robinlovelace** [comment] 2020-07-22 11:27
Sure. Also tried

```
npm start
```

Which resulted in:

![image](https://user-images.githubusercontent.com/1825120/88171123-b9656c00-cc16-11ea-8aed-bdd56fa8d17e.png)

**Comment by layik** [comment] 2020-07-22 11:28
Yes, that is correct. But that is only front-end and data is not served. I could add that to the README too. including the image.

**Comment by Robinlovelace** [comment] 2020-07-22 11:28
Giving it another go...

**Comment by layik** [comment] 2020-07-22 11:29
Right, updated both above comment and plumber. Should be "**reproducible**" now.

**Comment by Robinlovelace** [comment] 2020-07-22 11:30
Here's a reproducible asciinema cast of what I tried: https://asciinema.org/a/o9l4z0eN7zv9diUvrn5MZhStk

**Comment by Robinlovelace** [comment] 2020-07-22 11:30
Result, almost there...

![image](https://user-images.githubusercontent.com/1825120/88171418-2f69d300-cc17-11ea-8703-eb39a239343d.png)

**Comment by Robinlovelace** [comment] 2020-07-22 11:31
Code to reproduce that:

```zsh
asciinema rec
git pull
Rscript -e 'geoplumber::gp_build()'
Rscript 'run.R'
history | cut -c 8-
```

**Comment by layik** [comment] 2020-07-22 11:37
Working yet?

**Comment by layik** [comment] 2020-07-22 11:45
Right, need to slow down, changing the README was not right. Can we leave this for a couple of hours and then go through README, if it does not work then we have a reproducibility issue. Right now data is not served because we changed the "production url" which being in the heat of comments I changed for no good reason. Back in few hours.

**Comment by Robinlovelace** [comment] 2020-07-22 11:54
> Can we leave this for a couple of hours and then go through README

Sure, I'll be patient. Ping me here when good to test again :+1:

**Comment by layik** [comment] 2020-07-22 12:20
Hi @Robinlovelace and team. Apologies for the above set of not-so-coherent set of comments, please run the three steps in README here and report if not 100% reproducible (tiles etc are not the focus of those three steps)
https://github.com/saferactive/saferactive-eatlas

If that does not work, my apologies and let us open an issue in the repo [itself](https://github.com/saferactive/saferactive-eatlas).

**Comment by Robinlovelace** [comment] 2020-07-22 13:14
Trying it now...

**Comment by Robinlovelace** [comment] 2020-07-22 13:17
See here for what I tried: https://asciinema.org/a/SOcGbv57CpAzmbOYBjzrzMR0X

**Comment by Robinlovelace** [comment] 2020-07-22 13:18
Reproducible example (I suggest making the example code in the README all in bash rather than R):

```r
cd /tmp
git clone git@github.com:saferactive/saferactive-eatlas
cd saferactive-eatlas
R
# r code from readme
```

**Comment by Robinlovelace** [comment] 2020-07-22 13:19
That gives:

![image](https://user-images.githubusercontent.com/1825120/88181172-5e3b7580-cc26-11ea-967e-9644c9f39852.png)


Can you try to reproduce this @layik ?

**Comment by layik** [comment] 2020-07-22 13:27
The first attempt is correct. Cannot specify own port without changing it in front. Hence focus on port matching in README. If port is busy normally a `gp_kill_process()` can free it up. May not work due to user/sessions or other os process permissions.

**Comment by Robinlovelace** [comment] 2020-07-22 13:28
Ah OK. `80` is already in use.

**Comment by layik** [comment] 2020-07-22 13:30
No need to build every time. Just once will do.

**Comment by Robinlovelace** [comment] 2020-07-22 13:33
Do I need to free up port 80 first? Should be 'port agnostic' no?'

**Comment by layik** [comment] 2020-07-22 13:34
Robin, it is port agnostic, but this is a repo that has to build a front end which is already hard coded. I cannot specify port during build and then during runtime and make sure they match. The only way to do this is to be strict with production code.

**Comment by layik** [comment] 2020-07-22 13:36
To kill a process on a port: `gp_kill_process(port = 80)` again it may not work and this is by design.

https://github.com/ATFutures/geoplumber/blob/0d1c51259087aa5ba246cfcb9d736772702055a8/R/utils.R#L247

**Comment by layik** [comment] 2020-07-22 13:45
Still no joy?

**Comment by Robinlovelace** [comment] 2020-07-22 14:05
Not had a chance to try yet...

**Comment by Robinlovelace** [comment] 2020-07-22 15:06
> Cannot specify own port without changing it in front.

Port 80 is not available. Can you change it in front to use a different port, e.g. 8015?

**Comment by Robinlovelace** [comment] 2020-07-22 15:07
> To kill a process on a port: `gp_kill_process(port = 80)` again it may not work and this is by design.
> 
> https://github.com/ATFutures/geoplumber/blob/0d1c51259087aa5ba246cfcb9d736772702055a8/R/utils.R#L247



I see:

```
lsof -ti tcp:80 
8708
 /tmp/saferactive-eatlas   master  ps -p 8708      
  PID TTY          TIME CMD
 8708 tty2     1-13:47:31 firefox

```

Is that a good idea to kill it with 

```
pkill -9 $(lsof -ti tcp:80)
```

?

**Comment by Robinlovelace** [comment] 2020-07-22 15:09
> I cannot specify port during build and then during runtime and make sure they match

Which line of code specifies the port? Could try changing it...

**Comment by layik** [comment] 2020-07-22 15:19
Do you want to try the typical dev environment?

**Comment by layik** [comment] 2020-07-22 15:24
Right now if we can't get those three steps working then no script will make sure this app runs. And I am gutted that it took us so long to get it running.

**Comment by layik** [comment] 2020-07-22 15:57
Let us take this discussion here please: https://github.com/saferactive/saferactive-eatlas/issues/4. It seems `geojsonsf` is making it worse but this changes nothing the README.

**Comment by layik** [comment] 2020-07-22 15:58
Closing the ticket might be a good idea now @Robinlovelace. It is just too big.

**Closed** 2020-07-22 16:01 UTC
