### ISSUE TITLE
Create space/time raster maps of crashes and distance cycled at 500m level

### ISSUE THREAD

**Issue by mem48** [saferactive/saferactive#48] opened 2020-10-14 14:47 UTC
All crashed
Commuter Times

**Comment by mem48** [comment] 2020-10-19 15:28
First crack at this: Cyclists killed or seriously injured in 2019 during rush hours (7 -10 am or 4 - 7 pm)

![image](https://user-images.githubusercontent.com/15819577/96472077-f34f0a00-1227-11eb-928b-2e64a586bcde.png)

As usual raster package is a pain in the neck

**Comment by mem48** [comment] 2020-10-19 15:33
All years (2010:2019)

![image](https://user-images.githubusercontent.com/15819577/96472812-ce0ecb80-1228-11eb-85eb-903bf24bf907.png)

**Comment by mem48** [comment] 2020-10-19 15:39
All casualties all years all modes

![image](https://user-images.githubusercontent.com/15819577/96473494-9fddbb80-1229-11eb-9efb-aef24154e7db.png)

**Comment by Robinlovelace** [comment] 2020-10-19 15:55
Promising start. Please link to the code + upload results and releases when happy with them. First impression: these results will be very useful for the project.

**Comment by mem48** [comment] 2020-10-20 14:18
Code: https://github.com/saferactive/saferactive/blob/master/code/rasters.R

Rasters: https://github.com/saferactive/saferactive/tree/master/rasters

Each raster is a brick, with one layer per year from 2010 to 2019

**Comment by mem48** [comment] 2020-10-20 14:20
For example the all modes, all times,  all severity map for 2019

![image](https://user-images.githubusercontent.com/15819577/96599417-d24dee00-12e7-11eb-9123-afef8b141676.png)

**Comment by Robinlovelace** [comment] 2020-10-20 17:21
> Rasters: https://github.com/saferactive/saferactive/tree/master/rasters

Fantastic but can you put large (~1MB+) files in the releases in future?

Each one is only ~2MB and this repo can be messy but it's good practice to separate code and data.

In terms of the results... This looks like a useful resource, great work!

**Comment by mem48** [comment] 2020-10-21 10:24
@Robinlovelace I've removed them and created a release, I also changed the data type to INT2U to reduce the file size to 600 - 1200 KB.

**Comment by mem48** [comment] 2020-10-21 14:49
To Do:

Rasterise the pct commuter rnet to the same resolution.

**Comment by Robinlovelace** [comment] 2020-10-21 20:31
Here's the equivalent map of cycling activity in London: 

![image](https://user-images.githubusercontent.com/1825120/96780493-af553400-13e4-11eb-87fa-f018dceacaf9.png)


> - [x] Rasterise the pct commuter rnet to the same resolution.

**Comment by Robinlovelace** [comment] 2020-10-21 20:45
Interactive result from reproducible script created in #50: https://rpubs.com/RobinLovelace/679364

**Comment by Robinlovelace** [comment] 2020-10-21 20:50
One question, any ideas based on the code in that PR, why there are lonely blobs? Guess: it's the way mapview visualises the data:

![image](https://user-images.githubusercontent.com/1825120/96785970-79fe1580-13e7-11eb-89f2-029bcb64aa67.png)

**Comment by Robinlovelace** [comment] 2020-10-21 21:00
Explanation: route network segments can be very long in rural areas meaning that their centroids are few and far between. This is another argument for calculating smoothed estimates of cycling levels (heads-up @joeytalbot) but for now I think both crash numbers and cycling levels are too low in such areas for it to be a priority. 

![image](https://user-images.githubusercontent.com/1825120/96786860-c138d600-13e8-11eb-8f77-8d66b72c9ba9.png)

**Comment by Robinlovelace** [comment] 2020-10-26 15:50
Variogram for London rnet data:

![image](https://user-images.githubusercontent.com/1825120/97195237-04a59280-17a3-11eb-8146-b61bc2d09f5d.png)

**Comment by Robinlovelace** [comment] 2020-10-26 15:55
With VM model fitted: 

![image](https://user-images.githubusercontent.com/1825120/97195852-b0e77900-17a3-11eb-9cf0-f656bee220a6.png)

**Comment by Robinlovelace** [comment] 2020-10-26 16:22
First pass of spatial interpolation based on toy data:

```
> system.time({
+   rnet_krige1 = gstat::krige(bicycle~1, rnet_lnd_1pcnt, grd, vm, nmax = 9)
+ })
[using ordinary kriging]
   user  system elapsed 
  0.100   0.004   0.104 
> rnet_krige1
stars object with 2 dimensions and 2 attributes
attribute(s):
   var1.pred          var1.var     
 Min.   :   0.617   Min.   :44219  
 1st Qu.:   4.861   1st Qu.:54476  
 Median :   9.058   Median :57888  
 Mean   :  30.817   Mean   :56995  
 3rd Qu.:  22.289   3rd Qu.:60138  
 Max.   :1299.098   Max.   :63064  
 NA's   :4691       NA's   :4691   
dimension(s):
  from  to offset delta                       refsys point values    
x    1 114 503812   500 OSGB 1936 / British Natio...    NA   NULL [x]
y    1  87 200061  -500 OSGB 1936 / British Natio...    NA   NULL [y]
> plot(rnet_krige1)
```





![image](https://user-images.githubusercontent.com/1825120/97198904-4a645a00-17a7-11eb-8981-fd7f20124d76.png)

**Comment by Robinlovelace** [comment] 2020-10-26 16:24
From nmax = 9 to nmax = 30...

![image](https://user-images.githubusercontent.com/1825120/97199202-aaf39700-17a7-11eb-8be9-e838a8077be9.png)

![image](https://user-images.githubusercontent.com/1825120/97199246-b777ef80-17a7-11eb-8701-1d277fec88b7.png)

**Comment by Robinlovelace** [comment] 2020-10-26 17:09
``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library(gstat)
library(stars)
#> Loading required package: abind
u = "https://github.com/saferactive/saferactive/releases/download/0.1.1/rnet_lnd_1pcnt.Rds"
rnet_lnd = readRDS(url(u))
rnet_lnd
#> Simple feature collection with 698 features and 9 fields
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 506201.1 ymin: 157489.3 xmax: 554024 ymax: 197327
#> projected CRS:  OSGB 1936 / British National Grid
#> First 10 features:
#>       local_id bicycle govtarget_slc govnearmkt_slc gendereq_slc dutch_slc
#> 36469    36469       2             8              4            4        38
#> 72154    72154     296           464            509          415       992
#> 13692    13692      64            75             85           99       170
#> 51194    51194      10            10             15           20        38
#> 45023    45023       5            20             14           10        78
#> 14664    14664     140           166            189          198       270
#> 62204    62204      31            41             48           49       118
#> 48161    48161       7            18             16           14        83
#> 37306    37306       2            17             12            3        88
#> 8329      8329      10            34             32           19       144
#>       ebike_slc    length km_cycled_yr                  geometry
#> 36469        40  75.14911     76.05090 POINT (540554.4 184261.5)
#> 72154      1191  21.59051   3233.73959 POINT (532707.7 182641.9)
#> 13692       224  50.93146   1649.36427 POINT (526445.2 177201.8)
#> 51194        50 236.08443   1194.58721 POINT (533507.4 186557.7)
#> 45023        91 211.86509    536.01868 POINT (541408.3 180908.9)
#> 14664       342  14.72725   1043.27843 POINT (532361.8 186576.6)
#> 62204       193 550.77091   8639.39256 POINT (536944.7 176095.4)
#> 48161       104 194.18121    687.78986   POINT (534208 190667.8)
#> 37306        98  52.39301     53.02172 POINT (534251.2 195203.9)
#> 8329        249  81.10461    410.38932 POINT (540147.3 192165.4)
grd = st_bbox(rnet_lnd) %>%
  st_as_stars(dx = 500, dy = 500) %>%
  st_set_crs(27700) %>%
  st_crop(rnet_lnd) 
grd
#> stars object with 2 dimensions and 1 attribute
#> attribute(s):
#>     values     
#>  Min.   :0     
#>  1st Qu.:0     
#>  Median :0     
#>  Mean   :0     
#>  3rd Qu.:0     
#>  Max.   :0     
#>  NA's   :7051  
#> dimension(s):
#>   from to offset delta                       refsys point values    
#> x    1 96 506201   500 OSGB 1936 / British Natio...    NA   NULL [x]
#> y    1 80 197327  -500 OSGB 1936 / British Natio...    NA   NULL [y]
v = variogram(bicycle~1, rnet_lnd, cutoff = 10000)
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj
#> = prefer_proj): Discarded datum Unknown based on Airy 1830 ellipsoid in CRS
#> definition
#> Warning in showSRID(SRS_string, format = "PROJ", multiline = "NO", prefer_proj =
#> prefer_proj): Discarded datum OSGB 1936 in CRS definition
plot(v)
```

![](https://i.imgur.com/l8Uh1lq.png)

``` r
vm = fit.variogram(v, vgm(psill = "Sph", model = "Exp", range = 10000, nugget = 1))
plot(vm, cutoff = 10000)
```

![](https://i.imgur.com/467EaTV.png)

``` r
rnet_krige = gstat::krige(bicycle~1, rnet_lnd, grd, vm, nmax = 100)
#> [using ordinary kriging]
plot(rnet_lnd$geometry)
plot(rnet_krige, add = TRUE)
```

![](https://i.imgur.com/1dAonvA.png)

<sup>Created on 2020-10-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment] 2020-10-26 17:43
![image](https://user-images.githubusercontent.com/1825120/97208200-c7490100-17b2-11eb-858d-5eb3fc713b25.png)

**Comment by Robinlovelace** [comment] 2020-10-26 18:27
Before filling:

![image](https://user-images.githubusercontent.com/1825120/97212874-dd59c000-17b8-11eb-9564-28b2a7eb8fe6.png)

After

```r
fill.na = function(x, i=5) {
  if( is.na(x)[i] ) {
    return( round(mean(x, na.rm=TRUE),0) )
  } else {
    return(x[i])
  }
}  
raster_rnet_lnd_filled = focal(raster_rnet_lnd, w = matrix(1, 9, 9), fun = fill.na, pad = TRUE, na.rm = FALSE)
```

![image](https://user-images.githubusercontent.com/1825120/97212923-e8aceb80-17b8-11eb-8ee5-c2c803aae871.png)

**Comment by Robinlovelace** [comment] 2020-10-26 19:59
Interesting update @mem48 and @joeytalbot: ~30% of cycling activity in our dataset occurs in linestrings more than 500m long, meaning we need to split them up...
Here is a demonstration of an extreme case, covering 20 raster grid cells, leading to bad over-reporting of cycling in its centroid: 

![image](https://user-images.githubusercontent.com/1825120/97222093-bb1a6f00-17c5-11eb-82d6-ea406581f3c2.png)

**Comment by Robinlovelace** [comment] 2020-10-26 22:45
Before:

![image](https://user-images.githubusercontent.com/1825120/97236298-b57c5380-17dc-11eb-8524-67d64c14a83e.png)

After breaking up long (1km +) segments with https://docs.ropensci.org/stplanr/reference/line_breakup.html

![image](https://user-images.githubusercontent.com/1825120/97236345-cb8a1400-17dc-11eb-92b9-af04f69c2527.png)

**Comment by Robinlovelace** [comment] 2020-10-27 18:24
Heads-up, results from Hereford are looking WAY better:

![image](https://user-images.githubusercontent.com/1825120/97345101-9388dc80-1881-11eb-8bd6-cdb9bca1daa1.png)

vs

![image](https://user-images.githubusercontent.com/1825120/97345174-a9969d00-1881-11eb-8874-bf5dc6626510.png)

**Comment by Robinlovelace** [comment] 2020-10-27 18:26
Updated results for London also looking good:

![image](https://user-images.githubusercontent.com/1825120/97345445-fed2ae80-1881-11eb-8b1e-18553c1805c1.png)

**Comment by Robinlovelace** [comment] 2020-10-27 20:20
Here is code to get and view the results, for a rural and urban area:

```r
library(sf)
u = "https://github.com/saferactive/saferactive/releases/download/0.1.1/raster_rnet_bicycle.tif"
f = file.path("rasters", basename(u))
if(!file.exists(f)) {
  dir.create("rasters")
  download.file(u, f)
}
raster_rnet_bicycle = raster::raster(f)
hereford = pct::get_pct_zones("hereford-and-worcester") %>% sf::st_transform(27700)
raster_rnet_hereford = raster::crop(raster_rnet_bicycle, hereford)
mapview::mapview(raster_rnet_hereford)
london = pct::get_pct_zones("london") %>% sf::st_transform(27700)
raster_rnet_london = raster::crop(raster_rnet_bicycle, london)
mapview::mapview(raster_rnet_london)
```

Reproducible example:

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
u = "https://github.com/saferactive/saferactive/releases/download/0.1.1/raster_rnet_bicycle.tif"
f = file.path("rasters", basename(u))
if(!file.exists(f)) {
  dir.create("rasters")
  download.file(u, f)
}
raster_rnet_bicycle = raster::raster(f)
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj
#> = prefer_proj): Discarded datum Unknown based on Airy 1830 ellipsoid in CRS
#> definition
hereford = pct::get_pct_zones("hereford-and-worcester") %>% sf::st_transform(27700)
raster_rnet_hereford = raster::crop(raster_rnet_bicycle, hereford)
mapview::mapview(raster_rnet_hereford)
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj
#> = prefer_proj): Discarded ellps WGS 84 in CRS definition: +proj=merc +a=6378137
#> +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null
#> +wktext +no_defs +type=crs
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj =
#> prefer_proj): Discarded datum World Geodetic System 1984 in CRS definition
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj
#> = prefer_proj): Discarded ellps WGS 84 in CRS definition: +proj=merc +a=6378137
#> +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null
#> +wktext +no_defs +type=crs
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj =
#> prefer_proj): Discarded datum World Geodetic System 1984 in CRS definition
```

![](https://i.imgur.com/WYklYGj.png)

``` r
london = pct::get_pct_zones("london") %>% sf::st_transform(27700)
raster_rnet_london = raster::crop(raster_rnet_bicycle, london)
mapview::mapview(raster_rnet_london)
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj
#> = prefer_proj): Discarded ellps WGS 84 in CRS definition: +proj=merc +a=6378137
#> +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null
#> +wktext +no_defs +type=crs

#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj =
#> prefer_proj): Discarded datum World Geodetic System 1984 in CRS definition
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj
#> = prefer_proj): Discarded ellps WGS 84 in CRS definition: +proj=merc +a=6378137
#> +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null
#> +wktext +no_defs +type=crs
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj =
#> prefer_proj): Discarded datum World Geodetic System 1984 in CRS definition
```

![](https://i.imgur.com/wRrOfCb.png)

<sup>Created on 2020-10-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment] 2020-10-29 12:12
Heads-up @mem48 I'm closing this for now as we've got the exposure (for 2011) and crash numbers (2010-2019). Released as:

https://github.com/saferactive/saferactive/releases/download/0.1.1/raster_rnet_bicycle.tif

https://github.com/saferactive/saferactive/releases/download/0.1.1/cycle_commute_all.tif

And other tif files here: https://github.com/saferactive/saferactive/releases

**Closed by Robinlovelace** 2020-10-29 12:12 UTC

**Comment by Robinlovelace** [comment] 2020-12-16 00:54
KSI/bkm:

![image](https://user-images.githubusercontent.com/1825120/102290552-316f5e00-3f39-11eb-8120-07aa46cb8e75.png)

**Comment by Robinlovelace** [comment] 2020-12-16 00:56
At 4km resolution:

![image](https://user-images.githubusercontent.com/1825120/102290718-80b58e80-3f39-11eb-8a23-9bce6dbb7435.png)

**Comment by Robinlovelace** [comment] 2020-12-16 01:03
For all commute injuries, 500m res

![image](https://user-images.githubusercontent.com/1825120/102291180-76e05b00-3f3a-11eb-971e-e1ec7e3bef3b.png)

**Comment by Robinlovelace** [comment] 2020-12-16 01:04
2km resolution

![image](https://user-images.githubusercontent.com/1825120/102291276-b0b16180-3f3a-11eb-844b-a9690b1bfa74.png)

**Comment by Robinlovelace** [comment] 2020-12-16 01:41
![image](https://user-images.githubusercontent.com/1825120/102293822-c37a6500-3f3f-11eb-993d-b26271cfa8ef.png)
